// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the app follows the operating system accent or paints with its own
 * brand colour. Stored with the general settings and mirrored here so native
 * code can read it without touching the settings state.
 */
export type AccentPreference = "system" | "screenwide";
