// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a text box lines up its lines against each other. Only a text box
 * reads it; the other kinds carry the default the way a counter carries a
 * head it never draws.
 */
export type AnnotationAlign = "left" | "center" | "right";
