// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a redaction covers what is under it. Only a redaction reads it; the
 * other kinds carry the default the way they carry an alignment. Erase and
 * colour carry nothing of what was under the box: erase takes its surface
 * from the ring just outside the box, and colour uses the style's own.
 * Pixelate keeps each zone's colours and nothing of their layout. Classic
 * pixelation and blur keep more by design, which the editor says where
 * either is chosen.
 */
export type AnnotationRedaction = "erase" | "color" | "pixelate" | "pixelateClassic" | "blur";
