// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point in the screenshot source's pixel space.
 */
export type AnnotationPoint = { x: number, y: number, };
