// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationAlign } from "./AnnotationAlign";
import type { AnnotationHead } from "./AnnotationHead";
import type { AnnotationRedaction } from "./AnnotationRedaction";

/**
 * How an annotation is painted. The width is in points of the capture, drawn
 * at its scale straight into output pixels, so an annotation keeps its weight
 * on the canvas rather than growing with the picture, and weighs the same on
 * a 2x capture as on a 1x one.
 */
export type AnnotationStyle = { align: AnnotationAlign, 
/**
 * Whether a spotlight also blurs what lies outside it; the other kinds
 * carry `false`.
 */
blur: boolean, 
/**
 * `#rrggbb` or `#rrggbbaa`, straight alpha.
 */
color: string, 
/**
 * Which ends of an arrow carry a head.
 */
head: AnnotationHead, 
/**
 * Whether a highlight is drawn as a marker stroke by hand rather than as a
 * clean band, or a shape's outline as a pen stroke that misses its own
 * start; the other kinds carry `false`.
 */
handDrawn: boolean, 
/**
 * Whether a highlight is laid by hand over the box its drag spans, in
 * strokes the style's width tall, rather than fitted to the text under it;
 * the other kinds carry `false`.
 */
manual: boolean, 
/**
 * A redaction's, a shape's, a spotlight's or a magnifier's corner radius,
 * as a percentage of its box's shorter side from 0 to 50; the other kinds
 * carry zero.
 */
radius: number, redaction: AnnotationRedaction, 
/**
 * How far a spotlight's edge fades from lit to dim, as a percentage of its
 * box's shorter side from 0 to 50; the other kinds carry zero.
 */
softness: number, 
/**
 * Whether a magnifier's loupe casts a shadow onto the picture; the other
 * kinds carry `false`.
 */
shadow: boolean, 
/**
 * A blurred redaction's strength, a step from 1 to 5; the other kinds
 * carry zero.
 */
strength: number, 
/**
 * Whether a highlight tints what it covers, the way a felt marker does,
 * rather than recolouring the page it read; the other kinds carry `false`.
 */
tint: boolean, width: number, };
