// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinKeyframe } from "./PinKeyframe";

export type AnnotationPin = { pinnedMs: number, keyframes: Array<PinKeyframe>, };
