// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationShape } from "./AnnotationShape";
import type { AnnotationStyle } from "./AnnotationStyle";

/**
 * One drawn annotation, independent of its workspace and timing.
 */
export type Annotation = { 
/**
 * Whether a timed annotation draws itself in at the start of its clip and
 * undraws at the end. Stills have no clip to animate over, so they ignore
 * it and draw whole.
 */
animated: boolean, id: string, 
/**
 * Whether the draw tool made this annotation: a stroke, or what a held
 * stroke was taken for. Clear all takes these and leaves the rest. Left
 * out of a document where false.
 */
pen?: boolean, shape: AnnotationShape, style: AnnotationStyle, };
