// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds the compositor draws. The numbers are ABI: they are the C
 * `ScreenwideAnnotationKind` the macOS chrome reads, and the `kind == 1u`
 * tests in the WGSL annotation shaders. They travel inside the native
 * records as they are, so a value may never be renumbered. The serde names
 * are the `kind` tag of
 * `AnnotationShape` and what the live overlay's settings store, so a kind
 * is one word in a document, in settings, and over the native boundary.
 */
export type AnnotationKind = "arrow" | "counter" | "text" | "redact" | "highlight" | "shape" | "spotlight" | "draw" | "magnify" | "image";
