// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which ends of an arrow carry a head.
 */
export type AnnotationHead = "none" | "end" | "both";
