// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationHead } from "./AnnotationHead";
import type { AnnotationKind } from "./AnnotationKind";
import type { ToolbarPosition } from "./ToolbarPosition";

export type AnnotateSettings = { enabled: boolean, 
/**
 * Whether annotations survive the overlay closing. Off by default: the
 * overlay is normally toggled off to be rid of what is on screen.
 */
keepAnnotationsBetweenSessions: boolean, 
/**
 * What a fresh stroke is: the editor's own kind, so a tool added there
 * is the same word here and in the stored settings.
 */
defaultShape: AnnotationKind, 
/**
 * `#rrggbb` or `#rrggbbaa`, as a document stores it.
 */
defaultColor: string, defaultWidth: number, 
/**
 * The disc a fresh counter is drawn at, in points. Kept apart from the
 * arrow's stroke because they are different measurements of different
 * things: eight points of stroke would be a disc too small to hold a
 * number.
 */
defaultCounterSize: number, 
/**
 * Where a fresh counter's tail points, in radians clockwise from east. Live
 * annotations cannot be picked up again, so the aim is chosen before the
 * counter is dropped rather than turned afterwards.
 */
defaultCounterAngle: number, 
/**
 * Which ends of a fresh arrow carry a head. The editor's own type, so the
 * live overlay and the editor dress an arrow from the same value.
 */
defaultHead: AnnotationHead, 
/**
 * Whether a fresh highlight is drawn as a marker stroke by hand rather
 * than as a clean band.
 */
highlightHandDrawn: boolean, 
/**
 * Whether a fresh highlight is laid by hand over the box its drag spans
 * rather than fitted to the text under it.
 */
highlightManual: boolean, 
/**
 * Whether a fresh highlight tints what it covers rather than recolouring
 * the page under it.
 */
highlightTint: boolean, 
/**
 * Whether a fresh shape is drawn as a pen stroke by hand rather than as a
 * clean outline. Its own choice rather than the highlight's: a marker and
 * an outline are drawn by hand for different reasons.
 */
shapeHandDrawn: boolean, 
/**
 * How round a fresh shape's corners are, as a percentage of its shorter
 * side from 0 to 50: a square rounded all the way is a circle.
 */
shapeRadius: number, 
/**
 * Whether a fresh spotlight also blurs what lies outside it.
 */
spotlightBlur: boolean, 
/**
 * How round a fresh spotlight's corners are, as a percentage of its
 * shorter side from 0 to 50.
 */
spotlightRadius: number, 
/**
 * How far a fresh spotlight's edge fades, as a percentage of its shorter
 * side from 0 to 50.
 */
spotlightSoftness: number, toolbarPosition: ToolbarPosition | null, };
