// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppLocale = { 
/**
 * The translation in use: a folder in `locales/`, or the pseudo-locale.
 */
language: string, 
/**
 * What dates and numbers are written in: the computer's own locale when it
 * speaks the translation's language, so British English keeps day-first
 * dates under the American English translation; the translation's
 * otherwise, so they never mix two languages.
 */
formatLocale: string, };
