// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Background } from "./Background";

/**
 * A background under a name, as the background picker offers it.
 */
export type BackgroundPreset = { background: Background, id: string, name: string, };
