// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundMeshPoint } from "./BackgroundMeshPoint";

/**
 * What sits behind the picture, as a saved preset carries it.
 *
 * The three kinds are the three ways a canvas is filled: one colour, a mesh
 * of them, or a picture of your own. The editor spreads the same values
 * across the flat fields of an output canvas; a preset keeps them together,
 * since a preset is one background rather than part of one.
 */
export type Background = { "kind": "solid", color: string, } | { "kind": "image", path: string, } | { "kind": "mesh", colors: Array<string>, seed: number, warpPercent: number, 
/**
 * Which picture this paints. Presets saved before the ported generators
 * existed carry none, and are the app's own blob mesh.
 */
generator: string, lockedColors: Array<boolean>, 
/**
 * Present only for the classic mesh generator, which is the only one
 * that reads blobs; the others draw from their colours and seed alone.
 */
points?: Array<BackgroundMeshPoint>, };
