// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One blob of a mesh gradient, in shares of the canvas.
 */
export type BackgroundMeshPoint = { radiusX: number, radiusY: number, rotation: number, x: number, y: number, };
