// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A baked camera's placement, in the screen output's own pixels: the camera
 * image by its centre and width, and the crop window that frames it.
 */
export type CameraOverlaySettings = { cameraX: number, cameraY: number, cameraWidth: number, frameHeight: number, frameWidth: number, frameX: number, frameY: number, radiusPercent: number, };
