// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The crop tool's live result rectangle, in output pixels.
 *
 * Crop mode previews the whole source so the part being cropped away stays
 * visible. This is where the cropped layer itself lands inside that canvas,
 * so the compositor can draw it a second time with its real corner radius
 * and drop shadow.
 */
export type CropPreviewRect = { height: number, width: number, x: number, y: number, };
