// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CursorEffectSettings = { bake: boolean, clickAnimation: boolean, clipAtVideoEdge: boolean, motionBlur: boolean, smoothMovement: boolean, sizePercent: number, };
