// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which editor workspace something belongs to.
 *
 * A recording and a screenshot are held apart, each in its own workspace with
 * its own window, so one can sit waiting for a decision while the other is
 * being made. The enum is what keys them; growing past two is a matter of
 * widening it and the slot lookup, not of unpicking the callers.
 */
export type EditorKind = "recording" | "screenshot";
