// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorSnapshot } from "./EditorSnapshot";

/**
 * Every workspace at once, for a webview that has just come up and has no
 * event history to reconstruct them from.
 */
export type EditorSnapshots = { recording: EditorSnapshot, screenshot: EditorSnapshot, };
