// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorEffectSettings } from "./CursorEffectSettings";
import type { EditorArtifact } from "./EditorArtifact";
import type { EditorKind } from "./EditorKind";
import type { KeyboardEffectSettings } from "./KeyboardEffectSettings";
import type { RecordingExportChoices } from "./RecordingExportChoices";
import type { RecordingOutputSettings } from "./RecordingOutputSettings";
import type { ScreenshotOutputSettings } from "./ScreenshotOutputSettings";

export type EditorSnapshot = { artifact: EditorArtifact | null, cursorEffects: CursorEffectSettings, directory: string | null, keyboardEffects: KeyboardEffectSettings, recordingExportChoices: RecordingExportChoices, recordingOutput: RecordingOutputSettings | null, screenshotRadiusPercent: number, screenshotBackgroundRadiusPercent: number, screenshotOutput: ScreenshotOutputSettings | null, 
/**
 * Unset until a screenshot has been exported or copied once.
 */
screenshotDeleteProjectAfterExport: boolean | null, 
/**
 * Which workspace this describes. The change event is app-wide because the
 * recording bar listens to it too, so every receiver needs to know which of
 * its snapshots the payload replaces.
 */
workspace: EditorKind, };
