// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryRecordingKind } from "./PrimaryRecordingKind";
import type { RecordingAudioTrack } from "./RecordingAudioTrack";
import type { RecordingCamera } from "./RecordingCamera";
import type { RecordingProjectLook } from "./RecordingProjectLook";
import type { RecordingTimelineEdit } from "./RecordingTimelineEdit";
import type { ScreenshotItemSnapshot } from "./ScreenshotItemSnapshot";
import type { ScreenshotWorkspaceOutputSettings } from "./ScreenshotWorkspaceOutputSettings";

/**
 * What the window is told about the pending artifact. Deliberately without
 * pixels: the preview travels separately, as bytes.
 */
export type EditorArtifact = { "kind": "screenshot", id: number, items: Array<ScreenshotItemSnapshot>, 
/**
 * The canvas and layers saved in the project, which the window shows in
 * place of the remembered look.
 */
projectWorkspace?: ScreenshotWorkspaceOutputSettings | null, suggestedFileStem: string, extension: string, width: number, height: number, } | { "kind": "recording", audioTracks: Array<RecordingAudioTrack>, camera: RecordingCamera | null, canCompress: boolean, cursorDataVersion: number | null, hasCursorData: boolean, keyboardDataVersion: number | null, keyboardMaximumWidthUnits?: number | null, hasKeyboardData: boolean, id: number, suggestedFileStem: string, extension: string, width: number, height: number, durationMs: number, originalSizeBytes: number, 
/**
 * The working file, for the window to play through the asset protocol.
 * Scoped to the recordings directory in `tauri.conf.json`, which is the
 * only place this path can ever point.
 */
path: string, 
/**
 * The look saved in the project, which the window shows in place of the
 * remembered one.
 */
projectLook?: RecordingProjectLook | null, primaryKind: PrimaryRecordingKind, sourceScalePercent: number, timelineEdit?: RecordingTimelineEdit | null, timelineEditRevision?: number | null, };
