// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentPreference } from "./AccentPreference";
import type { BackgroundPreset } from "./BackgroundPreset";
import type { SceneTemplate } from "./SceneTemplate";

export type GeneralSettings = { accent: AccentPreference, 
/**
 * Colours the annotation tools were given that none of their presets
 * offers, newest last. Kept beside the saved backgrounds because they are
 * the same kind of thing: a choice made once that should be findable the
 * next time, rather than anything about the capture being edited.
 */
annotationColors: Array<string>, 
/**
 * Backgrounds saved from the editor's background picker, in the order
 * they were saved. The built-in ones are not kept here: they ship with
 * the app and would only go stale on disk.
 */
backgroundPresets: Array<BackgroundPreset>, 
/**
 * Where new projects are made. None is the default, a Screenwide folder in
 * the platform's Movies or Videos folder.
 */
projectDirectory: string | null, recordingDirectory: string | null, screenshotDirectory: string | null, openLocationAfterExport: boolean, recordScreenwideWindows: boolean, showRecordingConfidenceChecks: boolean, 
/**
 * Whether a new recording opens with zoom scenes made from its clicks and
 * typing.
 */
autoZoom: boolean, 
/**
 * Custom scene layouts saved from the Scene panel, oldest first, offered
 * in every recording.
 */
sceneTemplates: Array<SceneTemplate>, launchAtLogin: boolean, showRecordingBarOnLaunch: boolean, recordingCountdownSeconds: number, 
/**
 * How long Delayed Screenshot waits before the shutter fires.
 */
screenshotDelaySeconds: number, };
