// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlideAction } from "./GlideAction";
import type { GlidePhase } from "./GlidePhase";
import type { GlideRegion } from "./GlideRegion";

/**
 * The detector's complete observable state after one input or timer event.
 */
export type GlideDetection = { 
/**
 * A rest completed and this result still accepts the next step.
 */
becameReady: boolean, changed: boolean, pending: GlideAction | null, phase: GlidePhase, region: GlideRegion | null, };
