// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A committed destination, as a span of grid cells. `grid_cols` is however many
 * columns the detector was showing when the fingers lifted.
 */
export type GlideRegion = { colStart: number, colSpan: number, gridCols: number, rowStart: number, rowSpan: number, };
