// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlideControl } from "./GlideControl";

export type GlideSettings = { enabled: boolean, mouseModifier: GlideControl, monitorsModifier: GlideControl, spacesModifier: GlideControl, thirdsModifier: GlideControl, 
/**
 * Uniform gap between placed windows, in logical pixels.
 */
windowGap: number, cursorFollows: boolean, haptics: boolean, doubleTapCenter: boolean, };
