// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line's band, in source pixels. `left` is never past `right` nor `top`
 * past `bottom`: every edit writes a band back that way round.
 */
export type HighlightBand = { left: number, top: number, right: number, bottom: number, };
