// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The page under a highlight: how bright its surface is, and how bright the
 * ink printed on it, each from 0 to 1 as the compositor weighs a colour's
 * luminance. The recolouring maps the surface to the highlight's colour and
 * the ink to a colour that reads on it, so light text on a dark page and dark
 * text on a light one come out the same way.
 */
export type HighlightTone = { surface: number, ink: number, };
