// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a drop landed: the layer under it, and the point in that layer's
 * image-normalised space. The twin of `ImagePoint` in
 * `src/features/editor/images/image-api.ts`.
 */
export type ImagePoint = { layer: number, x: number, y: number, };
