// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorKind } from "./EditorKind";
import type { ImageArt } from "./ImageArt";
import type { ImagePoint } from "./ImagePoint";

export type ImageDrop = { workspace: EditorKind, art: ImageArt, at: ImagePoint | null, };
