// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an image's animation plays. Absent from an image whose picture does
 * not move. The twin of `ImagePlay` in
 * `src/features/editor/annotations/annotations.ts`.
 */
export type ImagePlay = { 
/**
 * How long one run of the animation lasts, in milliseconds.
 */
cycleMs: number, 
/**
 * How many frames one run has.
 */
frames: number, 
/**
 * The frame a still shows, counted from zero, and the one playback
 * starts on.
 */
frame: number, 
/**
 * Whether it plays through once rather than looping; its clip then lasts
 * exactly one run.
 */
once: boolean, };
