// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImagePlay } from "./ImagePlay";

/**
 * What an image shows: its picture by library id, and that picture's width
 * over its height. What the editor hands over as the picture the next
 * image is made with, along with how many pixels long the picture is on
 * its longer side, and how it plays where it moves. The twin of
 * `ImageArt` in `src/features/editor/annotations/annotations.ts`.
 */
export type ImageArt = { asset: string, aspect: number, pixels?: number, play?: ImagePlay, };
