// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyboardEffectAnimation } from "./KeyboardEffectAnimation";
import type { KeyboardEffectAppearance } from "./KeyboardEffectAppearance";

export type KeyboardEffectSettings = { bake: boolean, animation: KeyboardEffectAnimation, appearance: KeyboardEffectAppearance, sizePercent: number, positionXPercent?: number, positionYPercent?: number, };
