// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyboardShortcutPositionRange = { centerX: number, centerY: number, endMs: number, shortcutId: number, startMs: number, sizePercent?: number, };
