// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeshGradientPoint = { radiusX: number, radiusY: number, rotation: number, x: number, y: number, };
