// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which microphone tool is working.
 */
export type MicrophoneTool = "autoVolume" | "noise" | "silences" | "studioSound" | "voice";
