// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MicrophoneTool } from "./MicrophoneTool";

/**
 * How far a microphone tool has got with the recording, 0 to 1.
 */
export type MicrophoneProgress = { artifactId: number, fraction: number, tool: MicrophoneTool, };
