// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MomentKind } from "./MomentKind";

export type MomentSettings = { kinds: Array<MomentKind>, 
/**
 * Whether holding a kind's shortcut records a voice note with it.
 */
voiceNotes: boolean, 
/**
 * Whether voice notes are transcribed. A preference alone: it never
 * downloads or removes a model, which Settings › Transcription owns.
 */
transcribeNotes: boolean, 
/**
 * The microphone notes are recorded from, by device id. Nothing means
 * the recording's own, or the system's default when it has none.
 */
noteMicrophone: string | null, };
