// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MomentKind = { 
/**
 * Stable across renames, so a recording's moments keep their kind.
 */
id: string, name: string, 
/**
 * `#rrggbb`.
 */
color: string, 
/**
 * The colour last chosen outside the palette, kept so it can be chosen
 * again after a palette colour, or nothing if none ever was.
 */
customColor: string | null, shortcut: string | null, };
