// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Size } from "./Size";

export type MonitorDetails = { id: number, name: string, layoutPosition: Position, layoutSize: Size, position: Position, physicalPosition: Position, physicalSize: Size, size: Size, scaleFactor: number, isPrimary: boolean, isBuiltin: boolean, };
