// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the microphone's noise is taken out.
 */
export type NoiseReduction = "off" | "on";
