// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A crop rectangle expressed as fractions of the captured source image.
 */
export type NormalizedSourceRect = { height: number, width: number, x: number, y: number, };
