// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OcrAction } from "./OcrAction";

export type OcrSettings = { enabled: boolean, bindings: { [key in OcrAction]?: string | null }, };
