// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionStatus } from "./PermissionStatus";

export type PermissionSnapshot = { accessibility: PermissionStatus, screenRecording: PermissionStatus, camera: PermissionStatus, microphone: PermissionStatus, };
