// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the annotation is to be at `ms`: moved by `dx` and `dy` source
 * pixels from where it was drawn. A redaction resized away from the frame
 * it was pinned on also says how far each of its edges - left, top, right,
 * bottom - sits outside the box it was drawn as, once moved there.
 *
 * An out-of-view keyframe says instead that the content cannot be seen from
 * `ms`: the annotation is hidden until the next keyframe, and nothing is
 * followed in between. Its movement means nothing.
 */
export type PinKeyframe = { ms: number, dx: number, dy: number, edges?: [number, number, number, number], outOfView?: boolean, };
