// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTrackKind } from "./AudioTrackKind";

export type PreparedAudioTrack = { kind: AudioTrackKind, label: string, 
/**
 * Which recorded track this describes, so the window can name it back when
 * it asks for a mix. Also what identifies the row on screen.
 */
streamIndex: number, waveform: Array<number>, };
