// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the browser lists projects from: the recent ones, a folder, or
 * Recently Deleted.
 */
export type ProjectSource = { "kind": "recent" } | { "kind": "folder", path: string, } | { "kind": "deleted" };
