// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectKind } from "./ProjectKind";
import type { ProjectTracks } from "./ProjectTracks";

/**
 * A project as the browser lists it, read from its manifest alone.
 */
export type ProjectSummary = { 
/**
 * Whether the manifest could be read. A project on a drive that is not
 * connected, or one that was moved away, is listed but cannot be opened.
 */
available: boolean, 
/**
 * When it goes on to the system Trash, for a project in Recently
 * Deleted; None elsewhere.
 */
expiresMs: number | null, durationMs: number | null, file: string, kind: ProjectKind | null, 
/**
 * When the manifest last changed, which is when the project was last
 * edited.
 */
modifiedMs: number | null, 
/**
 * Everything in the project's folder, in bytes: what keeping it costs.
 */
sizeBytes: number | null, 
/**
 * Kept from the replay buffer rather than recorded start to stop.
 */
replay: boolean, title: string, 
/**
 * None for a screenshot, and for a project that could not be read.
 */
tracks: ProjectTracks | null, };
