// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder the browser lists projects from.
 */
export type ProjectLocation = { 
/**
 * False for a folder that is not there, such as one on a drive that is not
 * connected.
 */
available: boolean, 
/**
 * The projects folder new recordings go into, as opposed to one the user
 * added.
 */
isDefault: boolean, name: string, 
/**
 * On a drive other than the one holding the user's home folder, such as
 * an external disk. A folder that is not there counts as one: a missing
 * location is almost always a drive that is not plugged in.
 */
onOtherDrive: boolean, path: string, };
