// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a recording captured, for its card to show at a glance.
 */
export type ProjectTracks = { camera: boolean, microphone: boolean, screen: boolean, systemAudio: boolean, };
