// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a project holds, as the browser draws it.
 */
export type ProjectKind = "audio" | "camera" | "screen" | "screenshot";
