// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingCamera = { durationMs: number, height: number, originalSizeBytes: number, path: string, width: number, };
