// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stretch of the recording Remove silences cut, in shares of the whole
 * recording, and the rate it played at before it was cut, which it plays at
 * again when it is restored.
 */
export type RecordingSilenceCut = { sourceStart: number, sourceEnd: number, playbackRate: number, };
