// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingPreviewPane } from "./RecordingPreviewPane";

export type RecordingPreviewLayout = { height: number, panes: Array<RecordingPreviewPane>, width: number, };
