// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingMode } from "./RecordingMode";
import type { RecordingStatus } from "./RecordingStatus";

/**
 * Epoch-millisecond timestamps are stamped by Rust so every window - including
 * ones that reload or join late - derives the same elapsed time.
 */
export type RecordingSnapshot = { status: RecordingStatus, mode: RecordingMode | null, countdownSecondsRemaining: number, startedAtMs: number | null, accumulatedMs: number, pausedAtMs: number | null, };
