// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingTimelineSegment = { id: number, sourceEnd: number, sourceStart: number, playbackRate?: number, };
