// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingScenePreset } from "./RecordingScenePreset";
import type { SceneBoxes } from "./SceneBoxes";
import type { SceneFraming } from "./SceneFraming";
import type { SceneRadius } from "./SceneRadius";
import type { SceneVariant } from "./SceneVariant";

export type RecordingSceneClip = { id: string, startMs: number, endMs: number, preset: RecordingScenePreset, 
/**
 * What part of the screen fills its box; the whole of it where unset.
 */
screen?: SceneFraming, 
/**
 * What part of the camera fills its box. Unset, a full scene keeps the
 * recording's own camera crop and an arrangement shows the whole camera.
 */
camera?: SceneFraming, 
/**
 * Set, a custom scene: the panes sit in these boxes instead of the
 * preset's, which a reset returns them to.
 */
boxes?: SceneBoxes, 
/**
 * The panes' corner radii in this scene, which a reset takes away.
 */
radius?: SceneRadius, 
/**
 * How the preset is laid out, each option its default where unset.
 */
variant?: SceneVariant, 
/**
 * Set on a zoom the auto zoom made that nobody has edited since. Making
 * the auto zooms again replaces these and leaves every other scene alone.
 */
auto?: true, };
