// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTrackVolume } from "./AudioTrackVolume";
import type { CameraOverlaySettings } from "./CameraOverlaySettings";
import type { CursorEffectSettings } from "./CursorEffectSettings";
import type { KeyboardEffectSettings } from "./KeyboardEffectSettings";
import type { RecordingOutputSettings } from "./RecordingOutputSettings";
import type { VideoTrack } from "./VideoTrack";

/**
 * `RecordingProjectLook` in `src/features/editor/types.ts`.
 */
export type RecordingProjectLook = { bakeCamera: boolean, cameraOverlay: CameraOverlaySettings, cursorEffects: CursorEffectSettings, keyboardEffects: KeyboardEffectSettings, recordingOutput: RecordingOutputSettings, 
/**
 * None for each where the recording's own default stands: every track
 * on, at full volume.
 */
audioTrackVolumes: Array<AudioTrackVolume> | null, enabledStreamIndices: Array<number> | null, enabledVideoTracks: Array<VideoTrack> | null, };
