// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { AnnotationPin } from "./AnnotationPin";
import type { AnnotationTrack } from "./AnnotationTrack";

export type RecordingAnnotationClip = { annotation: Annotation, trackId: AnnotationTrack, startMs: number, endMs: number, 
/**
 * Where the annotation follows the content it was placed on, when it
 * does. Only the screen's clips are pinned: the camera is a face, not a
 * page.
 */
pin?: AnnotationPin, 
/**
 * How long what the annotation draws along a path takes to draw in - the
 * whole of an arrow, a highlight or a shape, a text box's pointer - paced
 * by the editor from the path's length. It leaves over three quarters of
 * that. Absent from a clip the editor has not paced, which takes its kind's
 * own time, and from every counter and redaction, which grow into place.
 */
pathMs?: number, };
