// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewPaneKind } from "./PreviewPaneKind";

export type RecordingPreviewPane = { height: number, kind: PreviewPaneKind, sourceHeight: number, sourceWidth: number, width: number, x: number, y: number, };
