// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The twin of `RecordingScenePreset` in
 * `src/features/editor/recording/scenes/recording-scenes.ts`.
 */
export type RecordingScenePreset = "full" | "split-two-thirds" | "picture-in-picture" | "stacked" | "camera-only" | "screen-only";
