// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRect } from "./TextRect";

export type RecognizedQrCode = { bounds: TextRect, content: string, decodeError?: string, };
