// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RememberedCameraOverlay } from "./RememberedCameraOverlay";

/**
 * Recording export choices carried to the next recording.
 *
 * `None` means the choice has never been offered by an exported recording,
 * so the editor keeps its own default. An export only overwrites the choices
 * it offered: exporting a recording without a camera must not forget whether
 * the camera was baked last time there was one.
 */
export type RecordingExportChoices = { bakeCamera: boolean | null, cameraCompression: number | null, cameraOverlay: RememberedCameraOverlay | null, cameraResolutionScalePercent: number | null, collapseAudio: boolean | null, compression: number | null, deleteProjectAfterExport: boolean | null, 
/**
 * The output scale as a share of the "Original" scale, which is how the
 * choice is labelled. A raw percentage would pick a different size on a
 * display with another scale factor.
 */
resolutionScaleRatio: number | null, };
