// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTrackKind } from "./AudioTrackKind";

export type RecordingAudioTrack = { kind: AudioTrackKind, label: string, streamIndex: number, };
