// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Size } from "./Size";

export type Region = { position: Position, size: Size, };
