// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraOverlaySettings } from "./CameraOverlaySettings";

/**
 * A baked camera's placement with the screen canvas and camera size it was
 * measured against. Placement is in screen pixels, so another recording can
 * only reuse it once it is scaled onto that recording's own geometry, which
 * the editor does when it seeds the next capture.
 */
export type RememberedCameraOverlay = { cameraHeight: number, cameraWidth: number, overlay: CameraOverlaySettings, screenHeight: number, screenWidth: number, };
