// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplayStatus } from "./ReplayStatus";

export type ReplaySnapshot = { 
/**
 * Whether this platform has a replay buffer at all.
 */
available: boolean, lengthSeconds: number, 
/**
 * A clip is being written.
 */
saving: boolean, status: ReplayStatus, };
