// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RulerAction = "toggleCrosshair" | "copyColour" | "deleteMeasurement" | "copyMeasurement" | "undo" | "redo" | "stampHorizontal" | "stampVertical" | "guideVertical" | "guideHorizontal" | "cycleTolerance" | "measureRadius" | "toggleCenterlines";
