// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RulerAction } from "./RulerAction";

export type RulerSettings = { enabled: boolean, bindings: { [key in RulerAction]?: string | null }, };
