// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The corner of the screen a picture in picture's camera sits over.
 */
export type SceneCorner = "top-left" | "top-right" | "bottom-left" | "bottom-right";
