// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pane's box in a custom scene, as shares of the canvas's width and
 * height.
 */
export type SceneBox = { x: number, y: number, width: number, height: number, };
