// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The corner radius a scene gives each pane, as a share of the pane's
 * shorter side in percent, like the recording's own. A pane without one
 * keeps the recording's radius.
 */
export type SceneRadius = { screen?: number, camera?: number, };
