// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneBox } from "./SceneBox";

/**
 * Where a custom scene puts its panes in place of its preset's boxes, and
 * which of them is drawn in front. The camera keeps the recording's own box
 * where it has none, and is drawn in front unless `camera_behind` says
 * otherwise.
 */
export type SceneBoxes = { screen: SceneBox, camera?: SceneBox, cameraBehind?: true, };
