// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneBubbleSize } from "./SceneBubbleSize";
import type { SceneCameraSize } from "./SceneCameraSize";
import type { SceneCorner } from "./SceneCorner";

/**
 * A preset's options, each its default where unset.
 */
export type SceneVariant = { 
/**
 * The camera before the screen: on the left beside it, or above it.
 */
swap?: boolean, cameraSize?: SceneCameraSize, corner?: SceneCorner, size?: SceneBubbleSize, };
