// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneBoxes } from "./SceneBoxes";
import type { SceneRadius } from "./SceneRadius";

/**
 * Where a layout puts the panes and how round it makes them. How far a
 * scene zooms is the scene's own, so a template never holds a zoom; one
 * saved with a zoom before is read without it.
 */
export type SceneTemplate = { id: string, name: string, 
/**
 * The width over the height of the canvas the layout was made on, which
 * its boxes are shares of.
 */
canvasAspect: number, boxes: SceneBoxes, radius?: SceneRadius, };
