// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How big a picture in picture's camera is beside the screen.
 */
export type SceneBubbleSize = "small" | "large";
