// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a side by side or stacked pair the camera takes.
 */
export type SceneCameraSize = "third" | "two-thirds";
