// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneFraming = { 
/**
 * The point of the picture in the middle of its box, as shares of the
 * picture's width and height.
 */
focusX: number, focusY: number, 
/**
 * How far the picture is zoomed past the size that only just covers its
 * box: one shows as much of it as the box's shape allows.
 */
zoom: number, };
