// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";

export type ScreenshotItemSnapshot = { 
/**
 * The annotations the item starts with, in its own pixels.
 */
annotations: Array<Annotation>, height: number, id: number, width: number, };
