// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { CropPreviewRect } from "./CropPreviewRect";
import type { MeshGradientPoint } from "./MeshGradientPoint";
import type { NormalizedSourceRect } from "./NormalizedSourceRect";

/**
 * One layer's canvas and its placement in it.
 *
 * Placement is in output pixels rather than in shares of the canvas, so the
 * canvas can be resized without moving or rescaling anything placed in it.
 * The crop is the visible rectangle; the image behind it is given by its top
 * left corner and its width, its height following the source's aspect.
 */
export type ScreenshotOutputSettings = { 
/**
 * Annotations drawn over this layer, in the source's own pixel space.
 */
annotations: Array<Annotation>, backgroundColor: string, 
/**
 * A picture of your own behind the layers. Absent for every background
 * that is painted rather than loaded, and for settings written before
 * pictures could be chosen.
 */
backgroundImagePath: string | null, backgroundType: string, backgroundRadiusPercent: number, 
/**
 * The visible rectangle, in output pixels. Zero width or height marks a
 * settings blob written before placement moved into pixels.
 */
cropHeight: number, 
/**
 * While the crop tool is open the preview draws the whole uncropped source
 * flat as a ghost; this is the committed crop rectangle, in output pixels,
 * that the compositor draws over it with the real corner radius and drop
 * shadow. Only the crop-mode preview payload carries one - it is never
 * persisted and never reaches an export.
 */
cropPreview?: CropPreviewRect | null, cropWidth: number, cropX: number, cropY: number, dropShadow: boolean, height: number, 
/**
 * The whole image's top left corner and width, in output pixels.
 */
imageWidth: number, imageX: number, imageY: number, mode?: string | null, meshColors: Array<string>, 
/**
 * Which picture the mesh background paints. Settings written before the
 * ported generators existed carry none, and are the app's own blob mesh.
 */
meshGenerator: string, meshLockedColors: Array<boolean>, meshPoints: Array<MeshGradientPoint>, meshSeed: number, meshWarpPercent: number, radiusPercent: number, recenterInsetColor: string | null, sourceCrop: NormalizedSourceRect, width: number, };
