// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project's scrub strip file: its frames side by side, each the same
 * size.
 */
export type ScrubStripFile = { frameHeight: number, frameWidth: number, frames: number, path: string, };
