// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectorPlacement } from "./SelectorPlacement";

export type SelectorState = { expanded: boolean, focusContents: boolean, 
/**
 * True while the popover is open but still waiting to be ordered onscreen.
 * The webview reveals it once it has painted the matching content.
 */
placement: SelectorPlacement, revision: number, 
/**
 * Which selector the popover was sized and opened for, so the webview can
 * avoid revealing the previous mode's content.
 */
windowSelector: boolean, };
