// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlideSettings } from "./GlideSettings";
import type { OcrSettings } from "./OcrSettings";
import type { RulerSettings } from "./RulerSettings";
import type { ShortcutSettings } from "./ShortcutSettings";

/**
 * Return the same defaults used when native settings are first initialized.
 * The UI never has to maintain a second set of platform-specific bindings.
 */
export type ShortcutDefaults = { shortcuts: ShortcutSettings, glide: GlideSettings, ruler: RulerSettings, ocr: OcrSettings, };
