// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutBinding } from "./ShortcutBinding";

export type ShortcutSettings = { bindings: Array<ShortcutBinding>, };
