// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShortcutAction = "toggleRecordingBar" | "startStopRecording" | "pauseResumeRecording" | "saveReplay" | "takeScreenshot" | "takeScreenshotToClipboard" | "recognizeText" | "annotateOverlay" | "annotateClear" | "rulerOverlay";
