// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stretch of the recording Remove silences would cut, in milliseconds.
 */
export type SilenceCut = { startMs: number, endMs: number, };
