// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingMode } from "./RecordingMode";
import type { Region } from "./Region";

/**
 * Options assembled by the recording bar from the source and input stores.
 */
export type StartRecordingOptions = { mode: RecordingMode, monitorId: number | null, windowId: number | null, region: Region | null, showCursor: boolean, captureKeyboardShortcuts: boolean, systemAudio: boolean, systemAudioApplicationIds: Array<string>, systemAudioProcessIds: Array<number>, microphoneId: string | null, cameraId: string | null, cameraWidth: number | null, cameraHeight: number | null, cameraFps: number | null, cameraFlipped: boolean, 
/**
 * Anti-flicker for 50 Hz mains (PAL): the camera runs at a PAL cadence on
 * macOS and has its power line frequency control set on Windows.
 */
cameraPal: boolean, fps: number, };
