// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the microphone is rebuilt as a studio recording.
 */
export type StudioSound = "off" | "on";
