// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationPoint } from "./AnnotationPoint";

/**
 * A text box's pointer, held against its box rather than in the picture, so
 * it keeps its place on the box however the box is moved, retyped or resized.
 *
 * `along` is where the tip sits against the box in each axis, as a share of
 * the box's half size from its centre: -1 at the left or top edge, 1 at the
 * right or bottom. `reach` is how far past that edge the tip goes in each
 * axis, in ems of the box's type, and is zero in an axis the tip is inside
 * the box in. A pointer that reaches nowhere is not drawn, but keeps its
 * place, so its grip is where it was left.
 */
export type TextPointer = { along: AnnotationPoint, reach: AnnotationPoint, };
