// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a commit falls in the typing, which is what tells React to open and
 * close the edit gesture it groups the typing into.
 */
export type TextEditPhase = "begin" | "update" | "end";
