// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the user dragged the toolbar, in logical points from the top-left of
 * the display it was dropped on. Held per display so the toolbar comes back
 * where it was left on that screen, and falls back to top-centre on a
 * display it has never been dragged on.
 */
export type ToolbarPosition = { displayId: number, x: number, y: number, };
